version: "3.9"

services:
  backend:
    # platform: linux/amd64 
    container_name: chess-be
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile

    restart: always
    ports:
      - 3000
    env_file:
      - ./apps/backend/.env
  ws:
    # platform: linux/amd64 
    container_name: chess-ws
    build:
      context: .
      dockerfile: ./apps/ws/Dockerfile
    restart: always
    ports:
      - 8080
    env_file:
      - ./apps/ws/.env
  frontend:
    container_name: chess-fe
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: always
    ports:
      - 5173:5173